<a href="https://colab.research.google.com/github/kingketan9/CloudComputingLabs/blob/main/Ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.
Then compute the average of the array (there is a numpy function for this, np.mean()).


In [15]:
import numpy as np

arr = np.random.rand(10, 10)
print("The array is : \n",arr)

average = np.mean(arr)
print("The average of the array is : " ,average)

The array is : 
 [[0.81245704 0.19611507 0.0484416  0.27042493 0.44857714 0.75716962
  0.42046175 0.85735071 0.41443473 0.40450968]
 [0.64310692 0.03960726 0.07242141 0.55923561 0.32099921 0.75207157
  0.07309514 0.50107423 0.67931502 0.12524217]
 [0.69396901 0.7662527  0.7783005  0.57211441 0.25030796 0.27437145
  0.41777983 0.87082403 0.58818913 0.31015554]
 [0.38412743 0.42223043 0.99696041 0.45260666 0.63157957 0.30617835
  0.43062705 0.18657348 0.79468555 0.25862467]
 [0.50010084 0.09744535 0.59421045 0.8530272  0.7999576  0.99479626
  0.56729741 0.15876724 0.54989543 0.39023204]
 [0.34607635 0.63235071 0.69236927 0.79348698 0.53390004 0.31168298
  0.63381844 0.76812863 0.01465722 0.13145957]
 [0.20943177 0.21836908 0.3680157  0.74448076 0.21911565 0.56889201
  0.13233683 0.05918025 0.35409385 0.85486796]
 [0.1541278  0.95070037 0.29902285 0.09912612 0.65323233 0.41741706
  0.56176628 0.04961519 0.43536222 0.78744971]
 [0.59314313 0.43167702 0.35576796 0.01930485 0.3727409  0.0480

2. Create the array:

   [[1, 6, 11],

   [2, 7, 12],

   [3, 8, 13],

   [4, 9, 14],

   [5, 10, 15]]

   with out explicitly typing it in. 

   Now create a new array containing only its 2nd and 4th
   rows

In [35]:
arr = np.arange(1,16)
arr1 = arr.reshape(3,5)
arr2 = arr1.T
print("The array is : ", arr2)

print("\n")
rows = [1,3]
x = arr2[rows]
print(x)

The array is :  [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


[[ 2  7 12]
 [ 4  9 14]]


3. Create a 2d array with 1 on the border and 0 on the inside, e.g., like:

 1 1 1 1 1

 1 0 0 0 1

 1 0 0 0 1

 1 1 1 1 1


In [21]:
import numpy as np

array = np.ones((4, 4))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


4. Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up
to 90).

● Now create 3 new arrays with the sine, cosine, and tangent of the elements of the
first array

● Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays
above and compare to the original angles


In [17]:
import numpy as np

angles = np.arange(0, 91, 15)
print(angles)

sines = np.sin(np.deg2rad(angles))
print(sines)

cosines = np.cos(np.deg2rad(angles))
print(cosines)

tangents = np.tan(np.deg2rad(angles))
print(tangents)

inv_sines = np.rad2deg(np.arcsin(sines))
print(inv_sines)

inv_cosines = np.rad2deg(np.arccos(cosines))
print(inv_cosines)

inv_tangents = np.rad2deg(np.arctan(tangents))
print(inv_tangents)

[ 0 15 30 45 60 75 90]
[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]


5. Given the array:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
calculate the difference of each element with its neighbor.


In [18]:
import numpy as np
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
diff = np.diff(x)
print("The difference of each element with its neighbor : ", diff)

The difference of each element with its neighbor :  [-2  3  3  3 -4  6  2 -9]


6. Write a function to calculate the standard deviation for an input array, a

In [19]:
import numpy as np

def std(a):
    return np.std(a)

arr = [1,2,3,4,5,6,7,8,9]
print("The standard deviation of the array is : ", std(arr))

The standard deviation of the array is :  2.581988897471611
